name: ci/cd

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  MONGO_URL: ${{ secrets.MONGO_URL }}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  cicd:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install PNPM
      run: npm install -g pnpm
    - name: Install Project Dependencies
      run: npm run clean-install

      # playwright tests with Percy
    - name: Install Playwright Browsers
      run: cd enm && npx playwright install --with-deps

    - name: Run Visual Regression with Percy + Playwright
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      run: cd enm && npx percy exec -- npm run test:playwright
    
    - name: Start API server in background
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        PORT: 3000
      working-directory: ./api-enm
      run: |
        pnpm run start:ci &
        for i in {1..30}; do
          if curl -sf http://127.0.0.1:${PORT}/ >/dev/null; then
            echo "API is up"
            break
          fi
          echo "Waiting for API..."
          sleep 2
        done

    - name: Run Postman tests
      run: |
        pnpm dlx newman run tests/Rarelygroovy API.postman_collection \
          -e tests/local.env.json \
          --reporters cli,junit \
          --reporter-junit-export newman-results.xml


      # angular tests
    - name: Run Commit Tests
      run: cd enm && npm run test

    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
    - name: Install Railway CLI
      run: npm i -g @railway/cli
    - name: Deploy To Railway
      run: railway up --service=enm-project
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        